kind: Service
apiVersion: v1
metadata:
  name: postgres
  labels:
    name: postgres-service
    app: voting-app
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    name: postgres-pod
    app: voting-app

---
kind: Pod
apiVersion: v1
metadata:
  name: postgres-pod
  labels:
    name: postgres-pod
    app: voting-app
spec:
  containers:
    - name: postgres
      image: postgres
      ports:
        - containerPort: 5432
      env:
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "postgres"