kind: Service
apiVersion: v1
metadata:
  name: redis
  labels:
    name: redis-service
    app: voting-app
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: 6379

---
kind: Pod
apiVersion: v1
metadata:
  name: redis-pod
  labels:
    name: redis-pod
    app: voting-app
spec:
  containers:
    - name: redis
      image: redis
      ports:
        - containerPort: 6379
